### ISSUE TITLE
Cannot run

### ISSUE THREAD

**Issue by callzhang** [DeepSystems/pexels_downloader#1]
```
localhost:pexels_downloader lei$ docker-compose up
Starting pexelsdownloader_downloader_1 ... done
Attaching to pexelsdownloader_downloader_1
downloader_1  | Building cache index from "/images/cache"
downloader_1  | Index has been built: found 0 files in 8ms
downloader_1  | TypeError: Cannot read property 'parent' of null
downloader_1  |     at Function.exports.update (/app/node_modules/cheerio/lib/parse.js:69:26)
downloader_1  |     at module.exports (/app/node_modules/cheerio/lib/parse.js:19:11)
downloader_1  |     at Function.exports.load (/app/node_modules/cheerio/lib/static.js:27:14)
downloader_1  |     at parseImages (/app/dist/index.js:123:21)
downloader_1  |     at crawlImages (/app/dist/index.js:178:14)
downloader_1  |     at <anonymous>
pexelsdownloader_downloader_1 exited with code 0
```

**Comment by mkolomeychenko** [comment]
What if we push working docker image to the Docker Hub and add section on how to run it with one line?

**Comment by callzhang** [comment]
That might be a good idea:)

**Comment by joseortegalabra** [comment]
hello, Can you write the line that you use to fix it?. I'm beginner in js and I don't know how to write.
